I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 58, in script
    if Book:
  File "game/script.rpy", line 58, in <module>
    if Book:
NameError: name 'Book' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 58, in script
    if Book:
  File "/opt/renpy-7.3.5-sdk/renpy/ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "/opt/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/opt/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 58, in <module>
    if Book:
NameError: name 'Book' is not defined

Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
Ren'Py 7.3.5.606
magicaldog 1.0
Wed Aug 12 23:28:07 2020
